### ISSUE TITLE
Web

### ISSUE THREAD

**Issue by Zeenat30** [html5blank/html5blank#271]
Untitled prompt 

Prompt

Code me a java script web design site

SUBMIT

Response

Markdown

```html
<!DOCTYPE html>
<html>
<head>
<title>My Web Design Site</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
<header>
<h1>My Web Design Site</h1>
<nav>
<a href="#">Home</a>
<a href="#">About</a>
<a href="#">Services</a>
<a href="#">Portfolio</a>
<a href="#">Contact</a>
</nav>
</header>

<main>
<section id="home">
<h2>Welcome to My Web Design Site</h2>
<p>I am a professional web designer with over 10 years of experience. I specialize in creating beautiful, user-friendly websites that are optimized for search engines. I can help you create a website that will help you grow your business and reach your target audience.</p>
<a href="#" class="button">Learn More</a>
</section>

<section id="about">
<h2>About Me</h2>
<p>I am a passionate web designer who loves creating beautiful and functional websites. I am always up-to-date on the latest web design trends and technologies, and I am always looking for new ways to improve my skills. I am also a great communicator and I am always happy to answer any questions you may have.</p>
<a href="#" class="button">Contact Me</a>
</section>

<section id="services">
<h2>Services</h2>
<ul>
<li>Web Design</li>
<li>Web Development</li>
<li>Search Engine Optimization (SEO)</li>
<li>Social Media Marketing</li>
<li>Email Marketing</li>
</ul>
<a href="#" class="button">Learn More</a>
</section>

<section id="portfolio">
<h2>Portfolio</h2>
<div class="portfolio-items">
<div class="portfolio-item">
<img src="images/portfolio-item-1.jpg" alt="Portfolio Item 1">
<h3>Portfolio Item 1</h3>
<p>This is a brief description of the portfolio item.</p>
</div>
<div class="portfolio-item">
<img src="images/portfolio-item-2.jpg" alt="Portfolio Item 2">
<h3>Portfolio Item 2</h3>
<p>This is a brief description of the portfolio item.</p>
</div>
<div class="portfolio-item">
<img src="images/portfolio-item-3.jpg" alt="Portfolio Item 3">
<h3>Portfolio Item 3</h3>
<p>This is a brief description of the portfolio item.</p>
</div>
</div>
<a href="#" class="button">View More</a>
</section>

<section id="contact">
<h2>Contact Me</h2>
<form action="mailto:youremail@example.com" method="post">
<label for="name">Name:</label>
<input type="text" name="name" id="name">

<label for="email">Email:</label>
<input type="email" name="email" id="email">

<label for="message">Message:</label>
<textarea name="message" id="message"></textarea>

<input type="submit" value="Send">
</form>
</section>
</main>

<footer>
<p>Copyright &copy; 2023 My Web Design Site</p>
</footer>
</body>
</html>
```

```css
/* Reset styles */

* {
margin: 0;
padding: 0;
box-sizing: border-box;
}

/* Global styles */

body {
font-family: sans-serif;
line-height: 1.6;
color: #333;
}

a {
text-decoration: none;
color: #333;
}

h1, h2, h3, h4, h5, h6 {
font-weight: bold;
}

p {
margin-bottom: 1em;
}

ul {
list-style-type: none;
padding: 0;
}

li {
margin-bottom: 1em;
}

/* Header styles */

header {
background-color: #f1f1f1;
padding: 1em;
}

header h1 {
font-size: 2em;
}

header nav {
float: right;
}

header nav a {
margin-right: 1em;
font-size: 1.2em;
}

/* Main styles */

main {
padding: 1em;
}

section {
margin-bottom: 2em;
}

#home {
background-color: #f5f5f5;
padding: 2em;
}

#home h2 {
font-size: 2em;
}

#home p {
font-size: 1.2em;
}

#about {
background-color: #ffffff;
padding: 2em;
}

#about h2 {
font-size: 2em;
}

#about p {
font-size: 1.2em;
}

#services {
background-color: #f1f1f1;
padding: 2em;
}

#services h2 {
font-size: 2em;
}

#services ul {
list-style-position: inside;
padding-left: 1em;
}

#services li {
font-size: 1.2em;
}

#portfolio {
background-color: #ffffff;
padding: 2em;
}

#portfolio h2 {
font-size: 2em;
}

.portfolio-items {
display: flex;
flex-wrap: wrap;
justify-content: space-between;
}

.portfolio-item {
width: 25%;
margin-bottom: 1em;
}

.portfolio-item img {
width: 100%;
height: auto;
}

.portfolio-item h3 {
font-size: 1.2em;
margin-bottom: 0.5em;
}

.portfolio-item p {
font-size: 0.8em;
}

#contact {
background-color: #f1f1f1;
padding: 2em;
}

#contact h2 {
font-size: 2em;
}

#contact form {
width: 100%;
}

#contact label {
display: block;
margin-bottom: 0.5em;
}

#contact input, #contact textarea {
width: 100%;
padding: 0.5em;
margin-bottom: 1em;
}

#contact textarea {
height: 10em;
}

#contact input[type="submit"] {
background-color: #333;
color: #ffffff;
padding: 0.5em 1em;
border: none;
cursor: pointer;
}

/* Footer styles */

footer {
background-color: #f1f1f1;
padding: 1em;
}

footer p {
font-size: 0.8em;
}
```
